#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='vertice_app') THEN
    CREATE ROLE vertice_app LOGIN PASSWORD '${APP_DB_PASSWORD}';
  ELSE
    ALTER ROLE vertice_app PASSWORD '${APP_DB_PASSWORD}';
  END IF;
END
$$;
GRANT CONNECT ON DATABASE $POSTGRES_DB TO vertice_app;
GRANT USAGE ON SCHEMA public TO vertice_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO vertice_app;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO vertice_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO vertice_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE,SELECT ON SEQUENCES TO vertice_app;
SQL
