#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -v app_db_password="$APP_DB_PASSWORD" -v postgres_db="$POSTGRES_DB" <<'SQL'
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='vertice_app') THEN
    EXECUTE format('CREATE ROLE vertice_app LOGIN PASSWORD %L', :'app_db_password');
  ELSE
    EXECUTE format('ALTER ROLE vertice_app PASSWORD %L', :'app_db_password');
  END IF;
END
$$;

ALTER ROLE vertice_app NOSUPERUSER NOBYPASSRLS NOCREATEROLE NOCREATEDB NOREPLICATION;
GRANT CONNECT ON DATABASE  :"postgres_db" TO vertice_app;
GRANT USAGE ON SCHEMA public TO vertice_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO vertice_app;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO vertice_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO vertice_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE,SELECT ON SEQUENCES TO vertice_app;
SQL
