const express=require('express');
const jwt=require('jsonwebtoken');
const crypto=require('crypto');
const Database=require('better-sqlite3');
if(process.env.NODE_ENV==='production'&&(!process.env.JWT_SECRET||!process.env.OWNER_LOGIN||!process.env.OWNER_PASSWORD))throw new Error('JWT_SECRET, OWNER_LOGIN e OWNER_PASSWORD são obrigatórios em produção.');
const db=new Database(process.env.DB_PATH||'vertice.db');
const originalListen=express.application.listen;let installed=false;
const err=(res,status,error)=>res.status(status).json({error});
const token=req=>{const h=String(req.headers.authorization||'');return h.startsWith('Bearer ')?h.slice(7):'';};
const verify=req=>{try{const s=process.env.JWT_SECRET;if(!s)return null;return jwt.verify(token(req),s);}catch{return null;}};
const mode=v=>{const x=String(v||'comando').trim().toLowerCase();return ['comando','operacao','monitoramento'].includes(x)?x:null;};
const owner=u=>u?.role==='OWNER';
const customer=u=>owner(u)?'owner':u?.sub;
const month=v=>{const m=String(v||new Date().toISOString().slice(0,7));return /^\d{4}-(0[1-9]|1[0-2])$/.test(m)?m:null;};
function active(u){if(owner(u))return true;const s=db.prepare('SELECT status,current_period_end FROM subscriptions WHERE customer_id=? ORDER BY updated_at DESC LIMIT 1').get(u.sub);return Boolean(s&&s.status==='active'&&(!s.current_period_end||new Date(s.current_period_end)>=new Date()));}
function authSales(req,res,next){const u=verify(req);if(!u)return err(res,401,'Sessão inválida');if(u.role!=='CUSTOMER')return err(res,403,'Painel comercial necessário.');if(!active(u))return err(res,402,'Assinatura não está ativa.');req.user=u;next();}
function aiFallback(message,m){const x=String(message||'').toLowerCase();if(x.includes('venda')||x.includes('receita'))return{answer:`VÉRTICE — ${m}: foco em receita paga, ticket, conversão e pendências.`,actions:[{type:'sales',label:'Analisar vendas'}]};if(x.includes('produto')||x.includes('oferta'))return{answer:`VÉRTICE — ${m}: estruturar problema, público, proposta, MVP e teste.`,actions:[{type:'plan',label:'Estruturar oportunidade'}]};return{answer:`VÉRTICE — ${m}: comando recebido. Escopo limitado ao solicitado; demais configurações preservadas.`,actions:[{type:'command',label:'Enviar para operação'}]};}
async function aiReply(message,m){const key=process.env.VERTICE_AI_API_KEY||process.env.GROQ_API_KEY||process.env.OPENAI_API_KEY||'';const base=String(process.env.VERTICE_AI_BASE_URL||(process.env.GROQ_API_KEY?'https://api.groq.com/openai/v1':'')||(process.env.OPENAI_API_KEY?'https://api.openai.com/v1':'')).replace(/\/$/,'');if(!key||!base)return aiFallback(message,m);const model=process.env.VERTICE_AI_MODEL||(process.env.GROQ_API_KEY?'llama-3.3-70b-versatile':'gpt-4o-mini');const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{const r=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature:.2,messages:[{role:'system',content:`Você é o VÉRTICE, operador autônomo de negócios. Responda em português. Modo: ${m}. Analise antes de agir, não invente dados e preserve tudo que não foi solicitado.`},{role:'user',content:String(message||'').slice(0,6000)}]}),signal:c.signal});const d=await r.json();if(!r.ok)throw Error(`AI HTTP ${r.status}`);const a=String(d?.choices?.[0]?.message?.content||'').trim();if(!a)throw Error('Resposta vazia');return{answer:a,actions:[{type:'ai',label:'Análise concluída'}]};}catch(e){console.error('[vertice] AI:',e.message);return aiFallback(message,m);}finally{clearTimeout(t);}}
async function mp(path,options={}){if(!process.env.MERCADOPAGO_ACCESS_TOKEN)throw Error('Mercado Pago não configurado no servidor.');const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(`https://api.mercadopago.com${path}`,{...options,signal:c.signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.MERCADOPAGO_ACCESS_TOKEN}`,...(options.headers||{})}});const text=await r.text();let d={};try{d=text?JSON.parse(text):{};}catch{}if(!r.ok){const e=Error(`Mercado Pago: ${d?.message||d?.error||`HTTP ${r.status}`}`);e.status=r.status;throw e;}return d;}finally{clearTimeout(t);}}
function saleRef(customer,sale){const c=customer==='owner'?'owner':String(customer).replace(/-/g,'').toLowerCase();return`VTX-${c}-${String(sale).replace(/-/g,'').toLowerCase()}`;}
function paymentId(order){const p=Array.isArray(order?.transactions?.payments)?order.transactions.payments:[];const x=p.find(v=>['approved','processed','accredited'].includes(String(v?.status||'').toLowerCase()))||p[0];return x?.id?String(x.id):null;}
function saleState(order,amount){const paid=Number(order?.total_paid_amount||0)>=Number(amount);const ps=Array.isArray(order?.transactions?.payments)?order.transactions.payments:[];if((String(order?.status||'').toLowerCase()==='processed'&&paid)||ps.some(p=>['approved','processed','accredited'].includes(String(p?.status||'').toLowerCase())))return'paid';const s=String(order?.status||'').toLowerCase();return s==='expired'?'expired':(s==='cancelled'||s==='canceled')?'cancelled':'pending';}
async function syncSaleRecord(sale){const order=await mp(`/v1/orders/${encodeURIComponent(sale.mp_order_id)}`),status=saleState(order,sale.amount),pid=paymentId(order),now=new Date().toISOString();db.prepare('UPDATE sales SET status=?,mp_payment_id=COALESCE(?,mp_payment_id),paid_at=CASE WHEN ?="paid" THEN COALESCE(paid_at,?) ELSE paid_at END WHERE id=?').run(status,pid,status,now,sale.id);const existing=db.prepare('SELECT id FROM payment_orders WHERE sale_id=?').get(sale.id);if(existing)db.prepare('UPDATE payment_orders SET provider_payment_id=?,status=?,updated_at=? WHERE sale_id=?').run(pid,status,now,sale.id);return status;}
function install(app){if(installed)return;installed=true;
app.post('/ai/chat',async(req,res)=>{const u=verify(req),m=mode(req.body?.mode);if(!u)return err(res,401,'Sessão inválida');if(!active(u))return err(res,402,'Assinatura não está ativa.');const message=String(req.body?.message||'').trim();if(!message||message.length>6000||!m)return err(res,400,'Mensagem ou modo inválido.');res.json({ok:true,...await aiReply(message,m),executionPolicy:{scope:'somente_o_solicitado',preservar_demais_configuracoes:true}});});
app.post('/owner/devices/register',(req,res)=>{const u=verify(req);if(!owner(u))return err(res,403,'Acesso de proprietário necessário.');const id=String(req.body?.deviceId||'').trim(),m=mode(req.body?.mode),name=String(req.body?.deviceName||'').trim().slice(0,100);if(!id||!m||!name)return err(res,400,'deviceId, mode e deviceName são obrigatórios.');const old=db.prepare('SELECT customer_id FROM devices WHERE id=?').get(id);if(old&&old.customer_id!=='owner')return err(res,403,'Dispositivo pertence a outra conta.');const now=new Date().toISOString();if(old)db.prepare('UPDATE devices SET mode=?,device_name=?,last_seen_at=? WHERE id=?').run(m,name,now,id);else db.prepare('INSERT INTO devices VALUES(?,?,?,?,?,?)').run(id,'owner',name,m,now,now);res.json({ok:true,deviceId:id,mode:m});});
app.post('/owner/commands',(req,res)=>{const u=verify(req);if(!owner(u))return err(res,403,'Acesso de proprietário necessário.');const command=String(req.body?.command||'').trim(),m=mode(req.body?.mode),deviceId=String(req.body?.deviceId||'').trim();if(!command||command.length>2000||!m||!deviceId)return err(res,400,'Comando, modo e deviceId são obrigatórios.');const d=db.prepare('SELECT customer_id,mode FROM devices WHERE id=?').get(deviceId);if(!d||d.customer_id!=='owner')return err(res,403,'Dispositivo não pertence ao proprietário.');if(m==='operacao'&&d.mode!=='operacao')return err(res,409,'O dispositivo não está em OPERAÇÃO.');const id=crypto.randomUUID(),now=new Date().toISOString();db.prepare('INSERT INTO commands VALUES(?,?,?,?,?,?,?)').run(id,'owner',deviceId,m,command,'queued',now);res.status(202).json({id,status:'queued',message:'Comando recebido pelo VÉRTICE.'});});
app.post('/commands',(req,res)=>{const u=verify(req);if(!u)return err(res,401,'Sessão inválida');if(!active(u))return err(res,402,'Assinatura não está ativa.');const command=String(req.body?.command||'').trim(),m=mode(req.body?.mode),deviceId=String(req.body?.deviceId||'').trim();if(!command||command.length>2000||!m||!deviceId)return err(res,400,'Comando, modo e deviceId são obrigatórios.');const d=db.prepare('SELECT customer_id,mode FROM devices WHERE id=?').get(deviceId);if(!d||d.customer_id!==customer(u))return err(res,403,'Dispositivo não pertence à conta.');if(m==='operacao'&&d.mode!=='operacao')return err(res,409,'O dispositivo não está em OPERAÇÃO.');const id=crypto.randomUUID(),now=new Date().toISOString();db.prepare('INSERT INTO commands VALUES(?,?,?,?,?,?,?)').run(id,customer(u),deviceId,m,command,'queued',now);res.status(202).json({id,status:'queued',message:'Comando recebido pelo VÉRTICE.'});});
app.get('/commands',(req,res)=>{const u=verify(req);if(!u)return err(res,401,'Sessão inválida');const rows=db.prepare('SELECT id,device_id AS deviceId,mode,command,status,created_at AS createdAt FROM commands WHERE customer_id=? ORDER BY created_at DESC LIMIT 50').all(customer(u));res.json({commands:rows});});
app.get('/commands/next',(req,res)=>{const u=verify(req);if(!u)return err(res,401,'Sessão inválida');if(!active(u))return err(res,402,'Assinatura não está ativa.');const deviceId=String(req.query?.deviceId||'').trim();if(!deviceId)return err(res,400,'deviceId é obrigatório.');const d=db.prepare('SELECT id,customer_id,mode FROM devices WHERE id=?').get(deviceId);if(!d||d.customer_id!==customer(u)||d.mode!=='operacao')return err(res,403,'Terminal OPERAÇÃO não autorizado.');db.prepare('UPDATE devices SET last_seen_at=? WHERE id=?').run(new Date().toISOString(),deviceId);const row=db.prepare('SELECT id,command,mode,status FROM commands WHERE customer_id=? AND device_id=? AND mode="operacao" AND status="queued" ORDER BY created_at ASC LIMIT 1').get(customer(u),deviceId);if(!row)return res.json({ok:true,command:null});const changed=db.prepare('UPDATE commands SET status="running" WHERE id=? AND customer_id=? AND status="queued"').run(row.id,customer(u));if(!changed.changes)return res.json({ok:true,command:null});row.status='running';res.json({ok:true,command:row});});
app.post('/commands/:commandId/status',(req,res)=>{const u=verify(req);if(!u)return err(res,401,'Sessão inválida');if(!active(u))return err(res,402,'Assinatura não está ativa.');const id=String(req.params.commandId||'').trim(),status=String(req.body?.status||'').trim().toLowerCase(),message=String(req.body?.message||'').trim().slice(0,1000),deviceId=String(req.body?.deviceId||'').trim();if(!id||!['completed','failed'].includes(status)||!deviceId)return err(res,400,'Status ou deviceId inválido.');const c=db.prepare('SELECT id,customer_id,device_id,status FROM commands WHERE id=?').get(id);if(!c||c.customer_id!==customer(u)||c.device_id!==deviceId)return err(res,404,'Comando não encontrado para este dispositivo.');if(c.status==='completed'||c.status==='failed')return res.json({ok:true,status:c.status});db.prepare('UPDATE commands SET status=? WHERE id=? AND customer_id=? AND device_id=? AND status="running"').run(status,id,customer(u),deviceId);if(message)console.log(`[vertice] command ${id} ${status}: ${message}`);res.json({ok:true,status});});
app.get('/sales',authSales,(req,res)=>{const m=month(req.query?.month);if(!m)return err(res,400,'Mês inválido. Use YYYY-MM.');const rows=db.prepare('SELECT id,amount,product,channel,status,checkout_url AS checkoutUrl,paid_at AS paidAt,created_at AS createdAt FROM sales WHERE customer_id=? AND substr(created_at,1,7)=? ORDER BY created_at DESC LIMIT 100').all(req.user.sub,m);const t=db.prepare('SELECT COALESCE(SUM(CASE WHEN status="paid" THEN amount ELSE 0 END),0) gross,COUNT(CASE WHEN status="paid" THEN 1 END) paidCount,COUNT(*) totalCount FROM sales WHERE customer_id=? AND substr(created_at,1,7)=?').get(req.user.sub,m);res.json({month:m,sales:rows,summary:{grossRevenue:Number(t.gross||0),paidCount:Number(t.paidCount||0),totalCount:Number(t.totalCount||0)}});});
app.post('/sales/orders',authSales,async(req,res)=>{const product=String(req.body?.product||'').trim().slice(0,120),amount=Number(req.body?.amount),description=String(req.body?.description||product).trim().slice(0,500);if(!product||!Number.isFinite(amount)||amount<=0||amount>1000000)return err(res,400,'Informe produto e valor válido.');const saleId=crypto.randomUUID(),ref=saleRef(req.user.sub,saleId),now=new Date().toISOString();try{db.prepare('INSERT INTO sales(id,customer_id,amount,product,channel,status,created_at,external_reference) VALUES(?,?,?,?,?,?,?,?)').run(saleId,req.user.sub,amount,product,'mercado_pago','pending',now,ref);const order=await mp('/v1/orders',{method:'POST',headers:{'X-Idempotency-Key':saleId},body:JSON.stringify({type:'online',total_amount:amount.toFixed(2),external_reference:ref,processing_mode:'manual',items:[{title:product,description,quantity:1,unit_price:amount.toFixed(2)}]})});const oid=String(order.id||''),url=String(order.checkout_url||'');if(!oid||!url)throw Error('Mercado Pago não retornou checkout.');db.prepare('UPDATE sales SET mp_order_id=?,checkout_url=? WHERE id=?').run(oid,url,saleId);db.prepare('INSERT INTO payment_orders(id,sale_id,customer_id,provider,provider_order_id,status,amount,checkout_url,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),saleId,req.user.sub,'mercado_pago',oid,'pending',amount,url,now,now);res.status(201).json({saleId,orderId:oid,status:'pending',checkoutUrl:url});}catch(e){try{db.prepare('UPDATE sales SET status="failed" WHERE id=?').run(saleId);}catch{}res.status(e.status&&e.status<500?e.status:502).json({error:e.message||'Falha ao criar cobrança.'});}});
app.post('/sales/orders/:saleId/sync',authSales,async(req,res)=>{const sale=db.prepare('SELECT * FROM sales WHERE id=? AND customer_id=?').get(req.params.saleId,req.user.sub);if(!sale)return err(res,404,'Venda não encontrada.');if(!sale.mp_order_id)return err(res,400,'Venda sem pedido Mercado Pago.');try{const status=await syncSaleRecord(sale);res.json({saleId:sale.id,status,orderId:sale.mp_order_id});}catch(e){res.status(502).json({error:e.message||'Falha ao sincronizar venda.'});}});
app.get('/reports/monthly',authSales,(req,res)=>{const m=month(req.query?.month);if(!m)return err(res,400,'Mês inválido. Use YYYY-MM.');const c=req.user.sub,t=db.prepare('SELECT COALESCE(SUM(CASE WHEN status="paid" THEN amount ELSE 0 END),0) gross,COUNT(CASE WHEN status="paid" THEN 1 END) count FROM sales WHERE customer_id=? AND substr(created_at,1,7)=?').get(c,m),s=db.prepare('SELECT * FROM monthly_sales WHERE customer_id=? AND period_month=?').get(c,m)||{},gross=Number(t.gross||0),count=Number(t.count||0);res.json({report:{month:m,grossRevenue:gross,netRevenue:Number(s.net_revenue||gross),salesCount:count,activeSubscriptions:Number(s.active_subscriptions||0),cancellations:Number(s.cancellations||0),delinquent:Number(s.delinquent||0),ticketAverage:count?gross/count:0}});});
app.get('/ranking',authSales,(req,res)=>{const m=month(req.query?.month);if(!m)return err(res,400,'Mês inválido. Use YYYY-MM.');const rows=db.prepare('SELECT c.id,COALESCE(SUM(CASE WHEN s.status="paid" THEN s.amount ELSE 0 END),0) gross,COUNT(CASE WHEN s.status="paid" THEN 1 END) sales FROM customers c LEFT JOIN sales s ON s.customer_id=c.id AND substr(s.created_at,1,7)=? GROUP BY c.id ORDER BY gross DESC').all(m),i=rows.findIndex(r=>r.id===req.user.sub),x=rows[i]||{gross:0,sales:0};res.json({participation:'private_default',ranking:{position:i>=0?i+1:null,total:rows.length,score:Math.round(Number(x.gross)*.1+Number(x.sales)*2)},benchmark:{topScore:rows.length?Math.round(Number(rows[0].gross)*.1+Number(rows[0].sales)*2):0}});});
app.get('/admin/overview',(req,res)=>{const u=verify(req);if(!owner(u))return err(res,403,'Acesso de proprietário necessário.');const customers=db.prepare('SELECT COUNT(*) n FROM customers').get().n,activeSubs=db.prepare('SELECT COUNT(*) n FROM subscriptions WHERE status="active"').get().n,devices=db.prepare('SELECT COUNT(*) n FROM devices').get().n,commandsToday=db.prepare('SELECT COUNT(*) n FROM commands WHERE created_at>=date("now")').get().n,salesMonth=db.prepare('SELECT COALESCE(SUM(CASE WHEN status="paid" THEN amount ELSE 0 END),0) n FROM sales WHERE substr(created_at,1,7)=substr(date("now"),1,7)').get().n;res.json({customers,activeSubscriptions:activeSubs,devices,commandsToday,salesMonth:Number(salesMonth||0)});});
app.get('/admin/customers',(req,res)=>{const u=verify(req);if(!owner(u))return err(res,403,'Acesso de proprietário necessário.');const rows=db.prepare('SELECT c.id,c.email,c.created_at createdAt,COALESCE(s.status,"blocked") subscriptionStatus,COALESCE(s.plan,"-") plan,(SELECT COUNT(*) FROM devices d WHERE d.customer_id=c.id) devices,(SELECT COUNT(*) FROM commands x WHERE x.customer_id=c.id) commands FROM customers c LEFT JOIN subscriptions s ON s.customer_id=c.id').all();res.json({customers:rows});});
}
express.application.listen=function(...args){install(this);return originalListen.apply(this,args);};
