package com.vertice.launcher.network

import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONObject
import java.net.URLEncoder
import java.util.concurrent.TimeUnit
import kotlin.math.min

class VerticeApi(private val baseUrl: String) {
    private val http = OkHttpClient.Builder().connectTimeout(12, TimeUnit.SECONDS).readTimeout(25, TimeUnit.SECONDS).build()
    private val json = "application/json; charset=utf-8".toMediaType()
    var onAuthError: (() -> Unit)? = null
    var onSubscriptionError: (() -> Unit)? = null

    fun login(login: String, password: String): Result<AuthResult> = requestResult {
        val body=JSONObject().put("login",login).put("email",login).put("password",password).toString().toRequestBody(json)
        val req=Request.Builder().url("${clean()}/auth/login").post(body).build()
        http.newCall(req).execute().use{r->if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val o=JSONObject(r.body?.string().orEmpty());val c=o.optJSONObject("customer")?:error("Resposta de login inválida.");AuthResult(o.getString("token"),c.getString("id"),c.optString("email",login),o.optString("role","CUSTOMER"))}
    }
    fun status(token:String):Result<SubscriptionStatus> = getWithRetry { val req=authorized("/me",token).get().build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val o=JSONObject(r.body?.string().orEmpty());val s=o.optJSONObject("subscription");SubscriptionStatus(s?.optString("plan","basic")?:"basic",s?.optString("status","blocked")?:"blocked",s?.optString("currentPeriodEnd","")?:"")} }
    fun registerDevice(token:String,deviceId:String,mode:String,deviceName:String,owner:Boolean=false):Result<Unit> = getPostWithRetry { val body=JSONObject().put("deviceId",deviceId).put("mode",mode).put("deviceName",deviceName).toString().toRequestBody(json);val endpoint=if(owner)"/owner/devices/register" else "/devices/register";val req=authorized(endpoint,token).post(body).build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()))} }
    fun chat(token:String,message:String,mode:String):Result<AiReply> = requestResult { val body=JSONObject().put("message",message).put("mode",mode).toString().toRequestBody(json);val req=authorized("/ai/chat",token).post(body).build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val o=JSONObject(r.body?.string().orEmpty());val arr=o.optJSONArray("actions");val actions=buildList{if(arr!=null)for(i in 0 until arr.length()){val x=arr.opt(i);when(x){is JSONObject->add(x.optString("label").ifBlank{x.optString("type")});else->add(String.valueOf(x))}}};AiReply(o.optString("answer"),actions)} }
    fun sendCommand(token:String,command:String,mode:String,deviceId:String,imageBase64:String?=null,owner:Boolean=false):Result<CommandResult> = requestResult { val body=JSONObject().put("command",command).put("mode",mode).put("deviceId",deviceId).put("scope","somente_o_solicitado").put("preservar_demais_configuracoes",true).apply{if(imageBase64!=null)put("imageBase64",imageBase64)}.toString().toRequestBody(json);val endpoint=if(owner)"/owner/commands" else "/commands";val req=authorized(endpoint,token).post(body).build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val o=JSONObject(r.body?.string().orEmpty());val id=o.optString("id");if(id.isBlank())error("Backend não retornou o ID do comando.");CommandResult(id,o.optString("status"),o.optString("message"))} }
    fun commands(token:String):Result<List<CommandResult>> = getWithRetry { val req=authorized("/commands",token).get().build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val arr=JSONObject(r.body?.string().orEmpty()).optJSONArray("commands")?:return@use emptyList();buildList{for(i in 0 until arr.length()){val x=arr.getJSONObject(i);add(CommandResult(x.optString("id"),x.optString("status"),x.optString("message",x.optString("command",""))))}}} }
    fun nextCommand(token:String,deviceId:String):Result<QueuedCommand?> = getWithRetry { val req=authorized("/commands/next?deviceId=${URLEncoder.encode(deviceId,"UTF-8")}",token).get().build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val x=JSONObject(r.body?.string().orEmpty()).optJSONObject("command")?:return@use null;QueuedCommand(x.getString("id"),x.optString("command"),x.optString("mode"),x.optString("status"))} }
    fun updateCommandStatus(token:String,id:String,status:String,message:String,deviceId:String):Result<Unit> = requestResult { val body=JSONObject().put("status",status).put("message",message).put("deviceId",deviceId).toString().toRequestBody(json);val req=authorized("/commands/$id/status",token).post(body).build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()))} }
    fun monthlyReport(token:String):Result<SalesReport> = getWithRetry { val req=authorized("/reports/monthly",token).get().build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val o=JSONObject(r.body?.string().orEmpty()).optJSONObject("report")?:error("Relatório inválido.");SalesReport(o.optString("month"),o.optDouble("grossRevenue"),o.optDouble("netRevenue"),o.optInt("salesCount"),o.optInt("activeSubscriptions"),o.optInt("cancellations"),o.optInt("delinquent"),o.optDouble("ticketAverage"))} }
    fun ranking(token:String):Result<RankingInfo> = getWithRetry { val req=authorized("/ranking",token).get().build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val o=JSONObject(r.body?.string().orEmpty());val x=o.optJSONObject("ranking")?:error("Ranking inválido.");RankingInfo(if(x.isNull("position"))null else x.optInt("position"),x.optInt("total"),x.optInt("score"),o.optJSONObject("benchmark")?.optInt("topScore")?:0)} }
    fun adminOverview(token:String):Result<AdminOverview> = getWithRetry { val req=authorized("/admin/overview",token).get().build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val o=JSONObject(r.body?.string().orEmpty());AdminOverview(o.optInt("customers"),o.optInt("activeSubscriptions"),o.optInt("devices"),o.optInt("commandsToday"),o.optDouble("salesMonth"))} }
    fun adminCustomers(token:String):Result<List<AdminCustomer>> = getWithRetry { val req=authorized("/admin/customers",token).get().build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val arr=JSONObject(r.body?.string().orEmpty()).optJSONArray("customers")?:return@use emptyList();buildList{for(i in 0 until arr.length()){val o=arr.getJSONObject(i);add(AdminCustomer(o.optString("id"),o.optString("email"),o.optString("createdAt"),o.optString("subscriptionStatus"),o.optString("plan"),o.optInt("devices"),o.optInt("commands")))}}} }
    fun createSaleOrder(token:String,product:String,amount:Double,description:String?=null):Result<SaleCheckout> = requestResult { val body=JSONObject().put("product",product).put("amount",amount).apply{if(!description.isNullOrBlank())put("description",description)}.toString().toRequestBody(json);val req=authorized("/sales/orders",token).post(body).build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val o=JSONObject(r.body?.string().orEmpty());SaleCheckout(o.getString("saleId"),o.optString("orderId"),o.optString("status"),o.getString("checkoutUrl"))} }
    fun sales(token:String,month:String?=null):Result<SalesList> = getWithRetry { val suffix=if(month.isNullOrBlank())"" else "?month=${URLEncoder.encode(month,"UTF-8")}";val req=authorized("/sales$suffix",token).get().build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));val o=JSONObject(r.body?.string().orEmpty());val s=o.optJSONObject("summary")?:JSONObject();val arr=o.optJSONArray("sales");if(arr==null)return@use SalesList(o.optString("month"),s.optDouble("grossRevenue"),s.optInt("paidCount"),s.optInt("totalCount"),emptyList());val items=buildList{for(i in 0 until arr.length()){val x=arr.getJSONObject(i);add(SaleItem(x.optString("id"),x.optDouble("amount"),x.optString("product"),x.optString("status"),x.optString("checkoutUrl"),x.optString("paidAt"),x.optString("createdAt")))}};SalesList(o.optString("month"),s.optDouble("grossRevenue"),s.optInt("paidCount"),s.optInt("totalCount"),items)} }
    fun syncSale(token:String,saleId:String):Result<String> = requestResult { val req=authorized("/sales/orders/$saleId/sync",token).post("{}".toRequestBody(json)).build();http.newCall(req).execute().use{r->requireAuthState(r);if(!r.isSuccessful)error(readError(r.code,r.body?.string()));JSONObject(r.body?.string().orEmpty()).optString("status","pending")} }
    private fun clean()=baseUrl.trimEnd('/')
    private fun authorized(path:String,token:String)=Request.Builder().url("${clean()}$path").header("Authorization","Bearer $token")
    private fun requireAuthState(r:okhttp3.Response){when(r.code){401->{onAuthError?.invoke();error("Sessão expirada. Por favor, faça login novamente.")};402->{onSubscriptionError?.invoke();error("Assinatura não está ativa.")}}}
    private fun <T> requestResult(block:()->T):Result<T> = runCatching(block)
    private fun <T> retry(block:()->T):Result<T>{var last:Result<T>=Result.failure(Exception("Falha de rede."));var wait=150L;repeat(3){i->last=runCatching(block);if(last.isSuccess)return last;val m=last.exceptionOrNull()?.message.orEmpty();if(m.contains("Sessão expirada")||m.contains("Assinatura não está ativa"))return last;if(i<2){Thread.sleep(wait);wait=min(wait*3,1500L)}};return last}
    private fun <T> getWithRetry(block:()->T)=retry(block)
    private fun <T> getPostWithRetry(block:()->T)=retry(block)
    private fun readError(code:Int,body:String?):String=try{JSONObject(body?:"{}").optString("error").ifBlank{when{code==401->"Não autenticado";code==402->"Assinatura não está ativa";code==403->"Acesso negado";code==404->"Recurso não encontrado";code>=500->"Erro no servidor. Tente novamente.";else->"Erro HTTP $code"}}}catch(_:Exception){"Erro HTTP $code"}
}
data class AuthResult(val token:String,val customerId:String,val email:String,val role:String)
data class AiReply(val answer:String,val actions:List<String>)
data class SubscriptionStatus(val plan:String,val status:String,val currentPeriodEnd:String)
data class CommandResult(val id:String,val status:String,val message:String)
data class QueuedCommand(val id:String,val command:String,val mode:String,val status:String)
data class SalesReport(val month:String,val grossRevenue:Double,val netRevenue:Double,val salesCount:Int,val activeSubscriptions:Int,val cancellations:Int,val delinquent:Int,val ticketAverage:Double)
data class RankingInfo(val position:Int?,val total:Int,val score:Int,val topScore:Int)
data class AdminOverview(val customers:Int,val activeSubscriptions:Int,val devices:Int,val commandsToday:Int,val salesMonth:Double)
data class AdminCustomer(val id:String,val email:String,val createdAt:String,val subscriptionStatus:String,val plan:String,val devices:Int,val commands:Int)
data class SaleCheckout(val saleId:String,val orderId:String,val status:String,val checkoutUrl:String)
data class SaleItem(val id:String,val amount:Double,val product:String,val status:String,val checkoutUrl:String,val paidAt:String,val createdAt:String)
data class SalesList(val month:String,val grossRevenue:Double,val paidCount:Int,val totalCount:Int,val sales:List<SaleItem>)
